[build]
builder = "nixpacks"

[deploy]
startCommand = "NODE_ENV=development npx tsx server/index.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"