services:
  - type: web
    name: tv-tantrum-catalog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx tsx server/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health